### ISSUE TITLE
TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by dpriskorn** [konchunas/pyrs#15]
I tried transpiling a python script today and ran into this:
Traceback (most recent call last):
  File "./pyrs.py", line 20, in <module>
    rs = transpile(source)
  File "/home/egil/src/rust/python2rust/pyrs/transpiler.py", line 34, in transpile
    return transpiler.visit(tree)
  File "/home/egil/src/rust/python2rust/pyrs/clike.py", line 74, in visit
    return super(CLikeTranspiler, self).visit(node)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/egil/src/rust/python2rust/pyrs/transpiler.py", line 280, in visit_Module
    buf += [self.visit(b) for b in node.body]
  File "/home/egil/src/rust/python2rust/pyrs/transpiler.py", line 280, in <listcomp>
    buf += [self.visit(b) for b in node.body]
  File "/home/egil/src/rust/python2rust/pyrs/clike.py", line 74, in visit
    return super(CLikeTranspiler, self).visit(node)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/egil/src/rust/python2rust/pyrs/transpiler.py", line 193, in visit_Expr
    s = self.visit(node.value)
  File "/home/egil/src/rust/python2rust/pyrs/clike.py", line 74, in visit
    return super(CLikeTranspiler, self).visit(node)
  File "/usr/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/egil/src/rust/python2rust/pyrs/transpiler.py", line 133, in visit_Call
    args = ", ".join(args)
TypeError: sequence item 0: expected str instance, NoneType found
source: https://gitlab.com/-/snippets/2001904

**Comment by konchunas** [comment]
I found that commenting out `# print(f"Calculated net cost: {cost}kr")` helps.
I'll try to fix that a bit later.
