### ISSUE TITLE
expected str instance, NoneType found while visiting a function call that passes None as an argument

### ISSUE THREAD

**Issue by db48x** [konchunas/pyrs#4]
Traceback (most recent call last):
      File "../pyrs/pyrs.py", line 20, in <module>
        rs = transpile(source)
      File "/home/db48x/projects/pyrs/pyrs/transpiler.py", line 34, in transpile
        return transpiler.visit(tree)
      File "/home/db48x/projects/pyrs/pyrs/clike.py", line 52, in visit
        return super(CLikeTranspiler, self).visit(node)
      File "/usr/lib64/python3.7/ast.py", line 262, in visit
        return visitor(node)
      File "/home/db48x/projects/pyrs/pyrs/transpiler.py", line 272, in visit_Module
        buf += [self.visit(b) for b in node.body]
      File "/home/db48x/projects/pyrs/pyrs/transpiler.py", line 272, in <listcomp>
        buf += [self.visit(b) for b in node.body]
      File "/home/db48x/projects/pyrs/pyrs/clike.py", line 52, in visit
        return super(CLikeTranspiler, self).visit(node)
      File "/usr/lib64/python3.7/ast.py", line 262, in visit
        return visitor(node)
      File "/home/db48x/projects/pyrs/pyrs/transpiler.py", line 429, in visit_Assign
        elements = [self.visit(e) for e in node.value.elts]
      File "/home/db48x/projects/pyrs/pyrs/transpiler.py", line 429, in <listcomp>
        elements = [self.visit(e) for e in node.value.elts]
      File "/home/db48x/projects/pyrs/pyrs/clike.py", line 52, in visit
        return super(CLikeTranspiler, self).visit(node)
      File "/usr/lib64/python3.7/ast.py", line 262, in visit
        return visitor(node)
      File "/home/db48x/projects/pyrs/pyrs/transpiler.py", line 133, in visit_Call
        args = ", ".join(args)
    TypeError: sequence item 3: expected str instance, NoneType found

The args look like this:

    ['"bzr"', '".bzr"', '"bzr fast-export --no-plain %(basename)s"', None, None, 'None', 'None', '"bzr fast-import -"', '"bzr checkout"', 'set()', 'None', '"http://bazaar.canonical.com/en/"', '".bzrignore"', '"\n# A simulation of bzr default ignores, generated by reposurgeon.\n*.a\n*.o\n*.py[co]\n*.so\n*.sw[nop]\n*~\n.#*\n[#]*#\n__pycache__\nbzr-orphans\n# Simulated bzr default ignores end here\n"', '(VCS::nobug + VCS::bare_numeric)', '"Requires the bzr-fast-import plugin."']

The source code is this:

```
    VCS(name="bzr",
        subdirectory=".bzr",
        exporter="bzr fast-export --no-plain %(basename)s",
        styleflags={"export-progress", "no-nl-after-commit", "nl-after-comment"},
        extensions={"empty-directories","multiple-authors","commit-properties"},
        initializer=None,
        lister=None,
        importer="bzr fast-import -",
        checkout="bzr checkout",
        preserve=set(),
        authormap=None,
        project="http://bazaar.canonical.com/en/",
        ignorename=".bzrignore",
        dfltignores="""
# A simulation of bzr default ignores, generated by reposurgeon.
*.a
*.o
*.py[co]
*.so
*.sw[nop]
*~
.#*
[#]*#
__pycache__
bzr-orphans
# Simulated bzr default ignores end here
""",
        cookies=(VCS.nobug + VCS.bare_numeric,),
        notes="Requires the bzr-fast-import plugin."),
```

**Comment by konchunas** [comment]
Thanks for report!
Maybe this semi-viable solution, but should do it.
